### ISSUE TITLE
Checklist needed in Readme

### ISSUE THREAD

**Issue by ParthS007** [gabru-md/git-from-scratch#1]
There should be a checklist in documentation which will show the goals achieved and milestones to be covered.

**Comment by gabru-md** [comment]
sure, we must get along with adding it as well.

**Comment by gabru-md** [comment]
Random Comment for gitter testing

**Comment by geekyd** [comment]
We can have a checklist for goals:
- [ ] Create UI for the web app
- [ ] Add interface for terminal
- [ ] Add terminal emulation for git commands
- [ ] Add basic scenarios like fork, clone etc
- [ ] Add more scenarios like pull request, importance of commit messages. etc
- [ ] Add advanced scenarios like resolving merge conflicts
